#include "textflag.h"

// Code generated by scripts/gen_vectors.py. DO NOT EDIT.
//
// Uniform exception frame passed to isr_dump():
//   0(SP)  vector, 8(SP) error code (real or dummy), 16(SP) rip ...

TEXT isr_0(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $0
	JMP common<>(SB)

TEXT isr_1(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $1
	JMP common<>(SB)

TEXT isr_2(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $2
	JMP common<>(SB)

TEXT isr_3(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $3
	JMP common<>(SB)

TEXT isr_4(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $4
	JMP common<>(SB)

TEXT isr_5(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $5
	JMP common<>(SB)

TEXT isr_6(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $6
	JMP common<>(SB)

TEXT isr_7(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $7
	JMP common<>(SB)

TEXT isr_8(SB), NOSPLIT, $-8
	PUSHQ $8
	JMP common<>(SB)

TEXT isr_9(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $9
	JMP common<>(SB)

TEXT isr_10(SB), NOSPLIT, $-8
	PUSHQ $10
	JMP common<>(SB)

TEXT isr_11(SB), NOSPLIT, $-8
	PUSHQ $11
	JMP common<>(SB)

TEXT isr_12(SB), NOSPLIT, $-8
	PUSHQ $12
	JMP common<>(SB)

TEXT isr_13(SB), NOSPLIT, $-8
	PUSHQ $13
	JMP common<>(SB)

TEXT isr_14(SB), NOSPLIT, $-8
	PUSHQ $14
	JMP common<>(SB)

TEXT isr_15(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $15
	JMP common<>(SB)

TEXT isr_16(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $16
	JMP common<>(SB)

TEXT isr_17(SB), NOSPLIT, $-8
	PUSHQ $17
	JMP common<>(SB)

TEXT isr_18(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $18
	JMP common<>(SB)

TEXT isr_19(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $19
	JMP common<>(SB)

TEXT isr_20(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $20
	JMP common<>(SB)

TEXT isr_21(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $21
	JMP common<>(SB)

TEXT isr_22(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $22
	JMP common<>(SB)

TEXT isr_23(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $23
	JMP common<>(SB)

TEXT isr_24(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $24
	JMP common<>(SB)

TEXT isr_25(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $25
	JMP common<>(SB)

TEXT isr_26(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $26
	JMP common<>(SB)

TEXT isr_27(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $27
	JMP common<>(SB)

TEXT isr_28(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $28
	JMP common<>(SB)

TEXT isr_29(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $29
	JMP common<>(SB)

TEXT isr_30(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $30
	JMP common<>(SB)

TEXT isr_31(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $31
	JMP common<>(SB)

TEXT isr_32(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $32
	JMP common<>(SB)

TEXT isr_33(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $33
	JMP common<>(SB)

TEXT isr_34(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $34
	JMP common<>(SB)

TEXT isr_35(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $35
	JMP common<>(SB)

TEXT isr_36(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $36
	JMP common<>(SB)

TEXT isr_37(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $37
	JMP common<>(SB)

TEXT isr_38(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $38
	JMP common<>(SB)

TEXT isr_39(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $39
	JMP common<>(SB)

TEXT isr_40(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $40
	JMP common<>(SB)

TEXT isr_41(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $41
	JMP common<>(SB)

TEXT isr_42(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $42
	JMP common<>(SB)

TEXT isr_43(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $43
	JMP common<>(SB)

TEXT isr_44(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $44
	JMP common<>(SB)

TEXT isr_45(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $45
	JMP common<>(SB)

TEXT isr_46(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $46
	JMP common<>(SB)

TEXT isr_47(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $47
	JMP common<>(SB)

TEXT isr_48(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $48
	JMP common<>(SB)

TEXT isr_49(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $49
	JMP common<>(SB)

TEXT isr_50(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $50
	JMP common<>(SB)

TEXT isr_51(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $51
	JMP common<>(SB)

TEXT isr_52(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $52
	JMP common<>(SB)

TEXT isr_53(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $53
	JMP common<>(SB)

TEXT isr_54(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $54
	JMP common<>(SB)

TEXT isr_55(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $55
	JMP common<>(SB)

TEXT isr_56(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $56
	JMP common<>(SB)

TEXT isr_57(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $57
	JMP common<>(SB)

TEXT isr_58(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $58
	JMP common<>(SB)

TEXT isr_59(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $59
	JMP common<>(SB)

TEXT isr_60(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $60
	JMP common<>(SB)

TEXT isr_61(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $61
	JMP common<>(SB)

TEXT isr_62(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $62
	JMP common<>(SB)

TEXT isr_63(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $63
	JMP common<>(SB)

TEXT isr_64(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $64
	JMP common<>(SB)

TEXT isr_65(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $65
	JMP common<>(SB)

TEXT isr_66(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $66
	JMP common<>(SB)

TEXT isr_67(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $67
	JMP common<>(SB)

TEXT isr_68(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $68
	JMP common<>(SB)

TEXT isr_69(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $69
	JMP common<>(SB)

TEXT isr_70(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $70
	JMP common<>(SB)

TEXT isr_71(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $71
	JMP common<>(SB)

TEXT isr_72(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $72
	JMP common<>(SB)

TEXT isr_73(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $73
	JMP common<>(SB)

TEXT isr_74(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $74
	JMP common<>(SB)

TEXT isr_75(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $75
	JMP common<>(SB)

TEXT isr_76(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $76
	JMP common<>(SB)

TEXT isr_77(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $77
	JMP common<>(SB)

TEXT isr_78(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $78
	JMP common<>(SB)

TEXT isr_79(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $79
	JMP common<>(SB)

TEXT isr_80(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $80
	JMP common<>(SB)

TEXT isr_81(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $81
	JMP common<>(SB)

TEXT isr_82(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $82
	JMP common<>(SB)

TEXT isr_83(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $83
	JMP common<>(SB)

TEXT isr_84(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $84
	JMP common<>(SB)

TEXT isr_85(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $85
	JMP common<>(SB)

TEXT isr_86(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $86
	JMP common<>(SB)

TEXT isr_87(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $87
	JMP common<>(SB)

TEXT isr_88(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $88
	JMP common<>(SB)

TEXT isr_89(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $89
	JMP common<>(SB)

TEXT isr_90(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $90
	JMP common<>(SB)

TEXT isr_91(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $91
	JMP common<>(SB)

TEXT isr_92(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $92
	JMP common<>(SB)

TEXT isr_93(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $93
	JMP common<>(SB)

TEXT isr_94(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $94
	JMP common<>(SB)

TEXT isr_95(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $95
	JMP common<>(SB)

TEXT isr_96(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $96
	JMP common<>(SB)

TEXT isr_97(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $97
	JMP common<>(SB)

TEXT isr_98(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $98
	JMP common<>(SB)

TEXT isr_99(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $99
	JMP common<>(SB)

TEXT isr_100(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $100
	JMP common<>(SB)

TEXT isr_101(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $101
	JMP common<>(SB)

TEXT isr_102(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $102
	JMP common<>(SB)

TEXT isr_103(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $103
	JMP common<>(SB)

TEXT isr_104(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $104
	JMP common<>(SB)

TEXT isr_105(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $105
	JMP common<>(SB)

TEXT isr_106(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $106
	JMP common<>(SB)

TEXT isr_107(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $107
	JMP common<>(SB)

TEXT isr_108(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $108
	JMP common<>(SB)

TEXT isr_109(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $109
	JMP common<>(SB)

TEXT isr_110(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $110
	JMP common<>(SB)

TEXT isr_111(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $111
	JMP common<>(SB)

TEXT isr_112(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $112
	JMP common<>(SB)

TEXT isr_113(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $113
	JMP common<>(SB)

TEXT isr_114(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $114
	JMP common<>(SB)

TEXT isr_115(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $115
	JMP common<>(SB)

TEXT isr_116(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $116
	JMP common<>(SB)

TEXT isr_117(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $117
	JMP common<>(SB)

TEXT isr_118(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $118
	JMP common<>(SB)

TEXT isr_119(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $119
	JMP common<>(SB)

TEXT isr_120(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $120
	JMP common<>(SB)

TEXT isr_121(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $121
	JMP common<>(SB)

TEXT isr_122(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $122
	JMP common<>(SB)

TEXT isr_123(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $123
	JMP common<>(SB)

TEXT isr_124(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $124
	JMP common<>(SB)

TEXT isr_125(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $125
	JMP common<>(SB)

TEXT isr_126(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $126
	JMP common<>(SB)

TEXT isr_127(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $127
	JMP common<>(SB)

TEXT isr_128(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $128
	JMP common<>(SB)

TEXT isr_129(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $129
	JMP common<>(SB)

TEXT isr_130(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $130
	JMP common<>(SB)

TEXT isr_131(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $131
	JMP common<>(SB)

TEXT isr_132(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $132
	JMP common<>(SB)

TEXT isr_133(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $133
	JMP common<>(SB)

TEXT isr_134(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $134
	JMP common<>(SB)

TEXT isr_135(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $135
	JMP common<>(SB)

TEXT isr_136(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $136
	JMP common<>(SB)

TEXT isr_137(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $137
	JMP common<>(SB)

TEXT isr_138(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $138
	JMP common<>(SB)

TEXT isr_139(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $139
	JMP common<>(SB)

TEXT isr_140(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $140
	JMP common<>(SB)

TEXT isr_141(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $141
	JMP common<>(SB)

TEXT isr_142(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $142
	JMP common<>(SB)

TEXT isr_143(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $143
	JMP common<>(SB)

TEXT isr_144(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $144
	JMP common<>(SB)

TEXT isr_145(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $145
	JMP common<>(SB)

TEXT isr_146(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $146
	JMP common<>(SB)

TEXT isr_147(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $147
	JMP common<>(SB)

TEXT isr_148(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $148
	JMP common<>(SB)

TEXT isr_149(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $149
	JMP common<>(SB)

TEXT isr_150(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $150
	JMP common<>(SB)

TEXT isr_151(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $151
	JMP common<>(SB)

TEXT isr_152(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $152
	JMP common<>(SB)

TEXT isr_153(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $153
	JMP common<>(SB)

TEXT isr_154(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $154
	JMP common<>(SB)

TEXT isr_155(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $155
	JMP common<>(SB)

TEXT isr_156(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $156
	JMP common<>(SB)

TEXT isr_157(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $157
	JMP common<>(SB)

TEXT isr_158(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $158
	JMP common<>(SB)

TEXT isr_159(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $159
	JMP common<>(SB)

TEXT isr_160(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $160
	JMP common<>(SB)

TEXT isr_161(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $161
	JMP common<>(SB)

TEXT isr_162(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $162
	JMP common<>(SB)

TEXT isr_163(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $163
	JMP common<>(SB)

TEXT isr_164(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $164
	JMP common<>(SB)

TEXT isr_165(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $165
	JMP common<>(SB)

TEXT isr_166(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $166
	JMP common<>(SB)

TEXT isr_167(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $167
	JMP common<>(SB)

TEXT isr_168(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $168
	JMP common<>(SB)

TEXT isr_169(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $169
	JMP common<>(SB)

TEXT isr_170(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $170
	JMP common<>(SB)

TEXT isr_171(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $171
	JMP common<>(SB)

TEXT isr_172(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $172
	JMP common<>(SB)

TEXT isr_173(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $173
	JMP common<>(SB)

TEXT isr_174(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $174
	JMP common<>(SB)

TEXT isr_175(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $175
	JMP common<>(SB)

TEXT isr_176(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $176
	JMP common<>(SB)

TEXT isr_177(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $177
	JMP common<>(SB)

TEXT isr_178(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $178
	JMP common<>(SB)

TEXT isr_179(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $179
	JMP common<>(SB)

TEXT isr_180(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $180
	JMP common<>(SB)

TEXT isr_181(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $181
	JMP common<>(SB)

TEXT isr_182(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $182
	JMP common<>(SB)

TEXT isr_183(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $183
	JMP common<>(SB)

TEXT isr_184(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $184
	JMP common<>(SB)

TEXT isr_185(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $185
	JMP common<>(SB)

TEXT isr_186(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $186
	JMP common<>(SB)

TEXT isr_187(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $187
	JMP common<>(SB)

TEXT isr_188(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $188
	JMP common<>(SB)

TEXT isr_189(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $189
	JMP common<>(SB)

TEXT isr_190(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $190
	JMP common<>(SB)

TEXT isr_191(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $191
	JMP common<>(SB)

TEXT isr_192(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $192
	JMP common<>(SB)

TEXT isr_193(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $193
	JMP common<>(SB)

TEXT isr_194(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $194
	JMP common<>(SB)

TEXT isr_195(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $195
	JMP common<>(SB)

TEXT isr_196(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $196
	JMP common<>(SB)

TEXT isr_197(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $197
	JMP common<>(SB)

TEXT isr_198(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $198
	JMP common<>(SB)

TEXT isr_199(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $199
	JMP common<>(SB)

TEXT isr_200(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $200
	JMP common<>(SB)

TEXT isr_201(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $201
	JMP common<>(SB)

TEXT isr_202(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $202
	JMP common<>(SB)

TEXT isr_203(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $203
	JMP common<>(SB)

TEXT isr_204(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $204
	JMP common<>(SB)

TEXT isr_205(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $205
	JMP common<>(SB)

TEXT isr_206(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $206
	JMP common<>(SB)

TEXT isr_207(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $207
	JMP common<>(SB)

TEXT isr_208(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $208
	JMP common<>(SB)

TEXT isr_209(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $209
	JMP common<>(SB)

TEXT isr_210(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $210
	JMP common<>(SB)

TEXT isr_211(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $211
	JMP common<>(SB)

TEXT isr_212(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $212
	JMP common<>(SB)

TEXT isr_213(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $213
	JMP common<>(SB)

TEXT isr_214(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $214
	JMP common<>(SB)

TEXT isr_215(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $215
	JMP common<>(SB)

TEXT isr_216(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $216
	JMP common<>(SB)

TEXT isr_217(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $217
	JMP common<>(SB)

TEXT isr_218(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $218
	JMP common<>(SB)

TEXT isr_219(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $219
	JMP common<>(SB)

TEXT isr_220(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $220
	JMP common<>(SB)

TEXT isr_221(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $221
	JMP common<>(SB)

TEXT isr_222(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $222
	JMP common<>(SB)

TEXT isr_223(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $223
	JMP common<>(SB)

TEXT isr_224(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $224
	JMP common<>(SB)

TEXT isr_225(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $225
	JMP common<>(SB)

TEXT isr_226(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $226
	JMP common<>(SB)

TEXT isr_227(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $227
	JMP common<>(SB)

TEXT isr_228(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $228
	JMP common<>(SB)

TEXT isr_229(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $229
	JMP common<>(SB)

TEXT isr_230(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $230
	JMP common<>(SB)

TEXT isr_231(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $231
	JMP common<>(SB)

TEXT isr_232(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $232
	JMP common<>(SB)

TEXT isr_233(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $233
	JMP common<>(SB)

TEXT isr_234(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $234
	JMP common<>(SB)

TEXT isr_235(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $235
	JMP common<>(SB)

TEXT isr_236(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $236
	JMP common<>(SB)

TEXT isr_237(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $237
	JMP common<>(SB)

TEXT isr_238(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $238
	JMP common<>(SB)

TEXT isr_239(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $239
	JMP common<>(SB)

TEXT isr_240(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $240
	JMP common<>(SB)

TEXT isr_241(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $241
	JMP common<>(SB)

TEXT isr_242(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $242
	JMP common<>(SB)

TEXT isr_243(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $243
	JMP common<>(SB)

TEXT isr_244(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $244
	JMP common<>(SB)

TEXT isr_245(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $245
	JMP common<>(SB)

TEXT isr_246(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $246
	JMP common<>(SB)

TEXT isr_247(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $247
	JMP common<>(SB)

TEXT isr_248(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $248
	JMP common<>(SB)

TEXT isr_249(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $249
	JMP common<>(SB)

TEXT isr_250(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $250
	JMP common<>(SB)

TEXT isr_251(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $251
	JMP common<>(SB)

TEXT isr_252(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $252
	JMP common<>(SB)

TEXT isr_253(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $253
	JMP common<>(SB)

TEXT isr_254(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $254
	JMP common<>(SB)

TEXT isr_255(SB), NOSPLIT, $-8
	PUSHQ $0
	PUSHQ $255
	JMP common<>(SB)

TEXT common<>(SB), NOSPLIT, $-8
	CLD
	CLI
	MOVQ SP, DI
	MOVQ isr_dump_ptr(SB), AX
	CALL (AX)
loop:
	HLT
	JMP loop

// set by gdt_idt.c before lidt
GLOBL isr_dump_ptr(SB), NOPTR, $8
DATA isr_dump_ptr+0(SB)/8, $0

// void *isr_stub_table[256]
GLOBL isr_stub_table(SB), NOPTR|RODATA, $2048
DATA isr_stub_table+0(SB)/8, $isr_0(SB)
DATA isr_stub_table+8(SB)/8, $isr_1(SB)
DATA isr_stub_table+16(SB)/8, $isr_2(SB)
DATA isr_stub_table+24(SB)/8, $isr_3(SB)
DATA isr_stub_table+32(SB)/8, $isr_4(SB)
DATA isr_stub_table+40(SB)/8, $isr_5(SB)
DATA isr_stub_table+48(SB)/8, $isr_6(SB)
DATA isr_stub_table+56(SB)/8, $isr_7(SB)
DATA isr_stub_table+64(SB)/8, $isr_8(SB)
DATA isr_stub_table+72(SB)/8, $isr_9(SB)
DATA isr_stub_table+80(SB)/8, $isr_10(SB)
DATA isr_stub_table+88(SB)/8, $isr_11(SB)
DATA isr_stub_table+96(SB)/8, $isr_12(SB)
DATA isr_stub_table+104(SB)/8, $isr_13(SB)
DATA isr_stub_table+112(SB)/8, $isr_14(SB)
DATA isr_stub_table+120(SB)/8, $isr_15(SB)
DATA isr_stub_table+128(SB)/8, $isr_16(SB)
DATA isr_stub_table+136(SB)/8, $isr_17(SB)
DATA isr_stub_table+144(SB)/8, $isr_18(SB)
DATA isr_stub_table+152(SB)/8, $isr_19(SB)
DATA isr_stub_table+160(SB)/8, $isr_20(SB)
DATA isr_stub_table+168(SB)/8, $isr_21(SB)
DATA isr_stub_table+176(SB)/8, $isr_22(SB)
DATA isr_stub_table+184(SB)/8, $isr_23(SB)
DATA isr_stub_table+192(SB)/8, $isr_24(SB)
DATA isr_stub_table+200(SB)/8, $isr_25(SB)
DATA isr_stub_table+208(SB)/8, $isr_26(SB)
DATA isr_stub_table+216(SB)/8, $isr_27(SB)
DATA isr_stub_table+224(SB)/8, $isr_28(SB)
DATA isr_stub_table+232(SB)/8, $isr_29(SB)
DATA isr_stub_table+240(SB)/8, $isr_30(SB)
DATA isr_stub_table+248(SB)/8, $isr_31(SB)
DATA isr_stub_table+256(SB)/8, $isr_32(SB)
DATA isr_stub_table+264(SB)/8, $isr_33(SB)
DATA isr_stub_table+272(SB)/8, $isr_34(SB)
DATA isr_stub_table+280(SB)/8, $isr_35(SB)
DATA isr_stub_table+288(SB)/8, $isr_36(SB)
DATA isr_stub_table+296(SB)/8, $isr_37(SB)
DATA isr_stub_table+304(SB)/8, $isr_38(SB)
DATA isr_stub_table+312(SB)/8, $isr_39(SB)
DATA isr_stub_table+320(SB)/8, $isr_40(SB)
DATA isr_stub_table+328(SB)/8, $isr_41(SB)
DATA isr_stub_table+336(SB)/8, $isr_42(SB)
DATA isr_stub_table+344(SB)/8, $isr_43(SB)
DATA isr_stub_table+352(SB)/8, $isr_44(SB)
DATA isr_stub_table+360(SB)/8, $isr_45(SB)
DATA isr_stub_table+368(SB)/8, $isr_46(SB)
DATA isr_stub_table+376(SB)/8, $isr_47(SB)
DATA isr_stub_table+384(SB)/8, $isr_48(SB)
DATA isr_stub_table+392(SB)/8, $isr_49(SB)
DATA isr_stub_table+400(SB)/8, $isr_50(SB)
DATA isr_stub_table+408(SB)/8, $isr_51(SB)
DATA isr_stub_table+416(SB)/8, $isr_52(SB)
DATA isr_stub_table+424(SB)/8, $isr_53(SB)
DATA isr_stub_table+432(SB)/8, $isr_54(SB)
DATA isr_stub_table+440(SB)/8, $isr_55(SB)
DATA isr_stub_table+448(SB)/8, $isr_56(SB)
DATA isr_stub_table+456(SB)/8, $isr_57(SB)
DATA isr_stub_table+464(SB)/8, $isr_58(SB)
DATA isr_stub_table+472(SB)/8, $isr_59(SB)
DATA isr_stub_table+480(SB)/8, $isr_60(SB)
DATA isr_stub_table+488(SB)/8, $isr_61(SB)
DATA isr_stub_table+496(SB)/8, $isr_62(SB)
DATA isr_stub_table+504(SB)/8, $isr_63(SB)
DATA isr_stub_table+512(SB)/8, $isr_64(SB)
DATA isr_stub_table+520(SB)/8, $isr_65(SB)
DATA isr_stub_table+528(SB)/8, $isr_66(SB)
DATA isr_stub_table+536(SB)/8, $isr_67(SB)
DATA isr_stub_table+544(SB)/8, $isr_68(SB)
DATA isr_stub_table+552(SB)/8, $isr_69(SB)
DATA isr_stub_table+560(SB)/8, $isr_70(SB)
DATA isr_stub_table+568(SB)/8, $isr_71(SB)
DATA isr_stub_table+576(SB)/8, $isr_72(SB)
DATA isr_stub_table+584(SB)/8, $isr_73(SB)
DATA isr_stub_table+592(SB)/8, $isr_74(SB)
DATA isr_stub_table+600(SB)/8, $isr_75(SB)
DATA isr_stub_table+608(SB)/8, $isr_76(SB)
DATA isr_stub_table+616(SB)/8, $isr_77(SB)
DATA isr_stub_table+624(SB)/8, $isr_78(SB)
DATA isr_stub_table+632(SB)/8, $isr_79(SB)
DATA isr_stub_table+640(SB)/8, $isr_80(SB)
DATA isr_stub_table+648(SB)/8, $isr_81(SB)
DATA isr_stub_table+656(SB)/8, $isr_82(SB)
DATA isr_stub_table+664(SB)/8, $isr_83(SB)
DATA isr_stub_table+672(SB)/8, $isr_84(SB)
DATA isr_stub_table+680(SB)/8, $isr_85(SB)
DATA isr_stub_table+688(SB)/8, $isr_86(SB)
DATA isr_stub_table+696(SB)/8, $isr_87(SB)
DATA isr_stub_table+704(SB)/8, $isr_88(SB)
DATA isr_stub_table+712(SB)/8, $isr_89(SB)
DATA isr_stub_table+720(SB)/8, $isr_90(SB)
DATA isr_stub_table+728(SB)/8, $isr_91(SB)
DATA isr_stub_table+736(SB)/8, $isr_92(SB)
DATA isr_stub_table+744(SB)/8, $isr_93(SB)
DATA isr_stub_table+752(SB)/8, $isr_94(SB)
DATA isr_stub_table+760(SB)/8, $isr_95(SB)
DATA isr_stub_table+768(SB)/8, $isr_96(SB)
DATA isr_stub_table+776(SB)/8, $isr_97(SB)
DATA isr_stub_table+784(SB)/8, $isr_98(SB)
DATA isr_stub_table+792(SB)/8, $isr_99(SB)
DATA isr_stub_table+800(SB)/8, $isr_100(SB)
DATA isr_stub_table+808(SB)/8, $isr_101(SB)
DATA isr_stub_table+816(SB)/8, $isr_102(SB)
DATA isr_stub_table+824(SB)/8, $isr_103(SB)
DATA isr_stub_table+832(SB)/8, $isr_104(SB)
DATA isr_stub_table+840(SB)/8, $isr_105(SB)
DATA isr_stub_table+848(SB)/8, $isr_106(SB)
DATA isr_stub_table+856(SB)/8, $isr_107(SB)
DATA isr_stub_table+864(SB)/8, $isr_108(SB)
DATA isr_stub_table+872(SB)/8, $isr_109(SB)
DATA isr_stub_table+880(SB)/8, $isr_110(SB)
DATA isr_stub_table+888(SB)/8, $isr_111(SB)
DATA isr_stub_table+896(SB)/8, $isr_112(SB)
DATA isr_stub_table+904(SB)/8, $isr_113(SB)
DATA isr_stub_table+912(SB)/8, $isr_114(SB)
DATA isr_stub_table+920(SB)/8, $isr_115(SB)
DATA isr_stub_table+928(SB)/8, $isr_116(SB)
DATA isr_stub_table+936(SB)/8, $isr_117(SB)
DATA isr_stub_table+944(SB)/8, $isr_118(SB)
DATA isr_stub_table+952(SB)/8, $isr_119(SB)
DATA isr_stub_table+960(SB)/8, $isr_120(SB)
DATA isr_stub_table+968(SB)/8, $isr_121(SB)
DATA isr_stub_table+976(SB)/8, $isr_122(SB)
DATA isr_stub_table+984(SB)/8, $isr_123(SB)
DATA isr_stub_table+992(SB)/8, $isr_124(SB)
DATA isr_stub_table+1000(SB)/8, $isr_125(SB)
DATA isr_stub_table+1008(SB)/8, $isr_126(SB)
DATA isr_stub_table+1016(SB)/8, $isr_127(SB)
DATA isr_stub_table+1024(SB)/8, $isr_128(SB)
DATA isr_stub_table+1032(SB)/8, $isr_129(SB)
DATA isr_stub_table+1040(SB)/8, $isr_130(SB)
DATA isr_stub_table+1048(SB)/8, $isr_131(SB)
DATA isr_stub_table+1056(SB)/8, $isr_132(SB)
DATA isr_stub_table+1064(SB)/8, $isr_133(SB)
DATA isr_stub_table+1072(SB)/8, $isr_134(SB)
DATA isr_stub_table+1080(SB)/8, $isr_135(SB)
DATA isr_stub_table+1088(SB)/8, $isr_136(SB)
DATA isr_stub_table+1096(SB)/8, $isr_137(SB)
DATA isr_stub_table+1104(SB)/8, $isr_138(SB)
DATA isr_stub_table+1112(SB)/8, $isr_139(SB)
DATA isr_stub_table+1120(SB)/8, $isr_140(SB)
DATA isr_stub_table+1128(SB)/8, $isr_141(SB)
DATA isr_stub_table+1136(SB)/8, $isr_142(SB)
DATA isr_stub_table+1144(SB)/8, $isr_143(SB)
DATA isr_stub_table+1152(SB)/8, $isr_144(SB)
DATA isr_stub_table+1160(SB)/8, $isr_145(SB)
DATA isr_stub_table+1168(SB)/8, $isr_146(SB)
DATA isr_stub_table+1176(SB)/8, $isr_147(SB)
DATA isr_stub_table+1184(SB)/8, $isr_148(SB)
DATA isr_stub_table+1192(SB)/8, $isr_149(SB)
DATA isr_stub_table+1200(SB)/8, $isr_150(SB)
DATA isr_stub_table+1208(SB)/8, $isr_151(SB)
DATA isr_stub_table+1216(SB)/8, $isr_152(SB)
DATA isr_stub_table+1224(SB)/8, $isr_153(SB)
DATA isr_stub_table+1232(SB)/8, $isr_154(SB)
DATA isr_stub_table+1240(SB)/8, $isr_155(SB)
DATA isr_stub_table+1248(SB)/8, $isr_156(SB)
DATA isr_stub_table+1256(SB)/8, $isr_157(SB)
DATA isr_stub_table+1264(SB)/8, $isr_158(SB)
DATA isr_stub_table+1272(SB)/8, $isr_159(SB)
DATA isr_stub_table+1280(SB)/8, $isr_160(SB)
DATA isr_stub_table+1288(SB)/8, $isr_161(SB)
DATA isr_stub_table+1296(SB)/8, $isr_162(SB)
DATA isr_stub_table+1304(SB)/8, $isr_163(SB)
DATA isr_stub_table+1312(SB)/8, $isr_164(SB)
DATA isr_stub_table+1320(SB)/8, $isr_165(SB)
DATA isr_stub_table+1328(SB)/8, $isr_166(SB)
DATA isr_stub_table+1336(SB)/8, $isr_167(SB)
DATA isr_stub_table+1344(SB)/8, $isr_168(SB)
DATA isr_stub_table+1352(SB)/8, $isr_169(SB)
DATA isr_stub_table+1360(SB)/8, $isr_170(SB)
DATA isr_stub_table+1368(SB)/8, $isr_171(SB)
DATA isr_stub_table+1376(SB)/8, $isr_172(SB)
DATA isr_stub_table+1384(SB)/8, $isr_173(SB)
DATA isr_stub_table+1392(SB)/8, $isr_174(SB)
DATA isr_stub_table+1400(SB)/8, $isr_175(SB)
DATA isr_stub_table+1408(SB)/8, $isr_176(SB)
DATA isr_stub_table+1416(SB)/8, $isr_177(SB)
DATA isr_stub_table+1424(SB)/8, $isr_178(SB)
DATA isr_stub_table+1432(SB)/8, $isr_179(SB)
DATA isr_stub_table+1440(SB)/8, $isr_180(SB)
DATA isr_stub_table+1448(SB)/8, $isr_181(SB)
DATA isr_stub_table+1456(SB)/8, $isr_182(SB)
DATA isr_stub_table+1464(SB)/8, $isr_183(SB)
DATA isr_stub_table+1472(SB)/8, $isr_184(SB)
DATA isr_stub_table+1480(SB)/8, $isr_185(SB)
DATA isr_stub_table+1488(SB)/8, $isr_186(SB)
DATA isr_stub_table+1496(SB)/8, $isr_187(SB)
DATA isr_stub_table+1504(SB)/8, $isr_188(SB)
DATA isr_stub_table+1512(SB)/8, $isr_189(SB)
DATA isr_stub_table+1520(SB)/8, $isr_190(SB)
DATA isr_stub_table+1528(SB)/8, $isr_191(SB)
DATA isr_stub_table+1536(SB)/8, $isr_192(SB)
DATA isr_stub_table+1544(SB)/8, $isr_193(SB)
DATA isr_stub_table+1552(SB)/8, $isr_194(SB)
DATA isr_stub_table+1560(SB)/8, $isr_195(SB)
DATA isr_stub_table+1568(SB)/8, $isr_196(SB)
DATA isr_stub_table+1576(SB)/8, $isr_197(SB)
DATA isr_stub_table+1584(SB)/8, $isr_198(SB)
DATA isr_stub_table+1592(SB)/8, $isr_199(SB)
DATA isr_stub_table+1600(SB)/8, $isr_200(SB)
DATA isr_stub_table+1608(SB)/8, $isr_201(SB)
DATA isr_stub_table+1616(SB)/8, $isr_202(SB)
DATA isr_stub_table+1624(SB)/8, $isr_203(SB)
DATA isr_stub_table+1632(SB)/8, $isr_204(SB)
DATA isr_stub_table+1640(SB)/8, $isr_205(SB)
DATA isr_stub_table+1648(SB)/8, $isr_206(SB)
DATA isr_stub_table+1656(SB)/8, $isr_207(SB)
DATA isr_stub_table+1664(SB)/8, $isr_208(SB)
DATA isr_stub_table+1672(SB)/8, $isr_209(SB)
DATA isr_stub_table+1680(SB)/8, $isr_210(SB)
DATA isr_stub_table+1688(SB)/8, $isr_211(SB)
DATA isr_stub_table+1696(SB)/8, $isr_212(SB)
DATA isr_stub_table+1704(SB)/8, $isr_213(SB)
DATA isr_stub_table+1712(SB)/8, $isr_214(SB)
DATA isr_stub_table+1720(SB)/8, $isr_215(SB)
DATA isr_stub_table+1728(SB)/8, $isr_216(SB)
DATA isr_stub_table+1736(SB)/8, $isr_217(SB)
DATA isr_stub_table+1744(SB)/8, $isr_218(SB)
DATA isr_stub_table+1752(SB)/8, $isr_219(SB)
DATA isr_stub_table+1760(SB)/8, $isr_220(SB)
DATA isr_stub_table+1768(SB)/8, $isr_221(SB)
DATA isr_stub_table+1776(SB)/8, $isr_222(SB)
DATA isr_stub_table+1784(SB)/8, $isr_223(SB)
DATA isr_stub_table+1792(SB)/8, $isr_224(SB)
DATA isr_stub_table+1800(SB)/8, $isr_225(SB)
DATA isr_stub_table+1808(SB)/8, $isr_226(SB)
DATA isr_stub_table+1816(SB)/8, $isr_227(SB)
DATA isr_stub_table+1824(SB)/8, $isr_228(SB)
DATA isr_stub_table+1832(SB)/8, $isr_229(SB)
DATA isr_stub_table+1840(SB)/8, $isr_230(SB)
DATA isr_stub_table+1848(SB)/8, $isr_231(SB)
DATA isr_stub_table+1856(SB)/8, $isr_232(SB)
DATA isr_stub_table+1864(SB)/8, $isr_233(SB)
DATA isr_stub_table+1872(SB)/8, $isr_234(SB)
DATA isr_stub_table+1880(SB)/8, $isr_235(SB)
DATA isr_stub_table+1888(SB)/8, $isr_236(SB)
DATA isr_stub_table+1896(SB)/8, $isr_237(SB)
DATA isr_stub_table+1904(SB)/8, $isr_238(SB)
DATA isr_stub_table+1912(SB)/8, $isr_239(SB)
DATA isr_stub_table+1920(SB)/8, $isr_240(SB)
DATA isr_stub_table+1928(SB)/8, $isr_241(SB)
DATA isr_stub_table+1936(SB)/8, $isr_242(SB)
DATA isr_stub_table+1944(SB)/8, $isr_243(SB)
DATA isr_stub_table+1952(SB)/8, $isr_244(SB)
DATA isr_stub_table+1960(SB)/8, $isr_245(SB)
DATA isr_stub_table+1968(SB)/8, $isr_246(SB)
DATA isr_stub_table+1976(SB)/8, $isr_247(SB)
DATA isr_stub_table+1984(SB)/8, $isr_248(SB)
DATA isr_stub_table+1992(SB)/8, $isr_249(SB)
DATA isr_stub_table+2000(SB)/8, $isr_250(SB)
DATA isr_stub_table+2008(SB)/8, $isr_251(SB)
DATA isr_stub_table+2016(SB)/8, $isr_252(SB)
DATA isr_stub_table+2024(SB)/8, $isr_253(SB)
DATA isr_stub_table+2032(SB)/8, $isr_254(SB)
DATA isr_stub_table+2040(SB)/8, $isr_255(SB)

TEXT ·stubTablePtr(SB), NOSPLIT, $-8
	MOVQ $isr_stub_table(SB), AX
	RET
