#!/usr/bin/env python3
"""Generate GNU as assembly for the 256 IDT stubs + dispatch table.

Output: arch/x86_64/traps.S (committed artifact -- regenerate with
`python3 scripts/gen_vectors.py > arch/x86_64/traps.S` after editing).

Uniform exception frame passed to isr_dump():
  0(%rsp) vector, 8(%rsp) error code (real or dummy), 16(%rsp) rip ...
"""

HEADER = """\
/* arch/x86_64/traps.S -- 256 IDT stub vectors + common trampoline.
 *
 * Code generated by scripts/gen_vectors.py. DO NOT EDIT by hand.
 * Uniform exception frame passed to isr_dump():
 *   0(%rsp) vector, 8(%rsp) error code (real or dummy), 16(%rsp) rip ...
 */

.section .text

.macro ISR n err=0
isr_\\n:
.if \\err == 0
\tpushq $0                /* dummy error code */
.endif
\tpushq $\\n               /* vector number */
\tjmp isr_common
.endm

"""

COMMON = """
isr_common:
\tcld
\tcli
\tmovq %rsp, %rdi         /* struct frame * */
\tcall isr_dump
1:\thlt
\tjmp 1b

.section .rodata
.globl isr_stub_table
.align 8
isr_stub_table:
"""

ERRCODED = {8, 10, 11, 12, 13, 14, 17, 21, 29, 30}


def main():
    out = [HEADER]
    for v in range(256):
        if v in ERRCODED:
            out.append(f"ISR {v} err=1\n")
        else:
            out.append(f"ISR {v}\n")
    out.append(COMMON)
    for v in range(256):
        out.append(f"\t.quad isr_{v}\n")
    print("".join(out), end="")


if __name__ == "__main__":
    main()
