#!/usr/bin/env python3
"""Generate Plan 9 assembly for the 256 IDT stubs + dispatch table."""

HEADER = '''#include "textflag.h"

// Code generated by scripts/gen_vectors.py. DO NOT EDIT.
//
// Uniform exception frame passed to isr_dump():
//   0(SP)  vector, 8(SP) error code (real or dummy), 16(SP) rip ...

'''

STUB_NOERR = """TEXT isr_{v}(SB), NOSPLIT, $-8
\tPUSHQ $0
\tPUSHQ ${v}
\tJMP common<>(SB)

"""

STUB_ERR = """TEXT isr_{v}(SB), NOSPLIT, $-8
\tPUSHQ ${v}
\tJMP common<>(SB)

"""

ERRCODED = {8, 10, 11, 12, 13, 14, 17}


def main():
    out = [HEADER]
    for v in range(256):
        t = STUB_ERR if v in ERRCODED else STUB_NOERR
        out.append(t.format(v=v))

    out.append("""TEXT common<>(SB), NOSPLIT, $-8
\tCLD
\tCLI
\tMOVQ SP, DI
\tMOVQ isr_dump_ptr(SB), AX
\tCALL (AX)
loop:
\tHLT
\tJMP loop

// set by gdt_idt.c before lidt
GLOBL isr_dump_ptr(SB), NOPTR, $8
DATA isr_dump_ptr+0(SB)/8, $0

// void *isr_stub_table[256]
GLOBL isr_stub_table(SB), NOPTR|RODATA, $2048
""")
    for v in range(256):
        out.append(f"DATA isr_stub_table+{v*8}(SB)/8, $isr_{v}(SB)\n")

    # Assembly-implemented accessor referenced from shim.go's package
    # initializer — this is what keeps the stub bank alive in the archive.
    out.append("""
TEXT ·stubTablePtr(SB), NOSPLIT, $-8
\tMOVQ $isr_stub_table(SB), AX
\tRET
""")

    print("".join(out), end="")


if __name__ == "__main__":
    main()
